<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Mandate Pickup</title>
	<link rel="stylesheet" type="text/css" href="<?=base_url()?>assets/css/normalize.css" />
	<link rel="stylesheet" type="text/css" href="<?=base_url()?>assets/css/demo.css" />
	<link rel="stylesheet" type="text/css" href="<?=base_url()?>assets/css/component.css" />
</head>
<body>
	<div class="container">
		<div class="component">
	<table border="1px" cellspacing="0" cellpadding="5">
		<tr>
			<td>id</td>
			<td>investor_user_id</td>
			<td>investor_pan</td>
			<td>investor_name</td>
			<td>kyc_status</td>
			<td>kyc_status_description</td>
			<td>application_submit_date</td>
			<td>reg_form_download</td>
			<td>download_date</td>
			<td>investor_docs_upload</td>
			<td>doc_upload_date</td>
			<td>abcspl_activation_status</td>
			<td>status_date_abcspl</td>
			<td>rejection_reason_abcspl</td>
			<td>cams_kyc</td>
			<td>status_date_cams</td>
			<td>rejection_reason_cams</td>
			<td>karvy_kyc</td>
			<td>status_date_karvy</td>
			<td>rejection_reason_karvy</td>
			<td>franklin_kyc</td>
			<td>status_date_franklin</td>
			<td>rejection_reason_franklin</td>
			<td>sundaram_kyc</td>
			<td>status_dare_sundaram</td>
			<td>rejection_reason_sundaram</td>
			<td>account_status</td>
			<td>acount_status_date</td>
			<td>email_alert</td>
			<td>sms_alert</td>
			<td>document_received</td>
			<td>document_received_date</td>
			<td>rejected_date</td>
			<td>activation_date</td>
			<td>courier</td>
			<td>version_no</td>
			<td>second_applicant_pan</td>
			<td>second_applicant_name</td>
			<td>second_applicant_kyc_status</td>
			<td>second_applicant_kyc_status_description</td>
			<td>third_applicant_pan</td>
			<td>third_applicant_name</td>
			<td>third_applicant_kyc_status</td>
			<td>third_applicant_kyc_status_description</td>
			<td>gender</td>
			<td>investor_type</td>
			<td>investor_dob</td>
			<td>mode_of_holding</td>
			<td>nationality</td>
			<td>guardian_pan</td>
			<td>guardian_name</td>
			<td>guardian_kyc_status</td>
			<td>guardian_kyc_status_description</td>
			<td>guardian_rel_minor</td>
			<td>bank_name</td>
			<td>ifsc_code</td>
			<td>micr_code</td>
			<td>bank_account_holder_name</td>
			<td>bank_account_no</td>
			<td>bank_account_type</td>
			<td>bank_address</td>
			<td>applied_for_mandate</td>
			<td>applied_ecs_ach_both</td>
			<td>country</td>
			<td>pincode</td>
			<td>city</td>
			<td>state</td>
			<td>correspondence_address</td>
			<td>email_id</td>
			<td>mobile_no</td>
			<td>nominee_name</td>
			<td>nominee_rel_first_applicant</td>
			<td>status</td>
			<td>nominee_dob</td>
			<td>nominee_address</td>
			<td>nominee_guardian_name</td>
			<td>rel_with_nominee</td>
			<td>registration_date</td>
			<td>ecs_mandate_status</td>
			<td>ach_mandate_status</td>
			<td>login_username</td>
			<td>mode_of_application</td>
			<td>no_of_sip</td>
			<td>no_of_lumsum</td>
			<td>non_kyc_activation_remark</td>
			<td>myuniverse_ref_id</td>
			<td>myuniverse_email_id</td>
			<td>url</td>
			<td>utm</td>
			<td>product_page</td>
			<td>kyc_agency_status</td>
			<td>date_time</td>
		</tr>
		<?php
	foreach($investor_master_data as $investor_master_data_row){
		?>
		<tr>
			<td><?=$investor_master_data_row->id?></td>
			<td><?=$investor_master_data_row->investor_user_id?></td>
			<td><?=$investor_master_data_row->investor_pan?></td>
			<td><?=$investor_master_data_row->investor_name?></td>
			<td><?=$investor_master_data_row->kyc_status?></td>
			<td><?=$investor_master_data_row->kyc_status_description?></td>
			<td><?=$investor_master_data_row->application_submit_date?></td>
			<td><?=$investor_master_data_row->reg_form_download?></td>
			<td><?=$investor_master_data_row->download_date?></td>
			<td><?=$investor_master_data_row->investor_docs_upload?></td>
			<td><?=$investor_master_data_row->doc_upload_date?></td>
			<td><?=$investor_master_data_row->abcspl_activation_status?></td>
			<td><?=$investor_master_data_row->status_date_abcspl?></td>
			<td><?=$investor_master_data_row->rejection_reason_abcspl?></td>
			<td><?=$investor_master_data_row->cams_kyc?></td>
			<td><?=$investor_master_data_row->status_date_cams?></td>
			<td><?=$investor_master_data_row->rejection_reason_cams?></td>
			<td><?=$investor_master_data_row->karvy_kyc?></td>
			<td><?=$investor_master_data_row->status_date_karvy?></td>
			<td><?=$investor_master_data_row->rejection_reason_karvy?></td>
			<td><?=$investor_master_data_row->franklin_kyc?></td>
			<td><?=$investor_master_data_row->status_date_franklin?></td>
			<td><?=$investor_master_data_row->rejection_reason_franklin?></td>
			<td><?=$investor_master_data_row->sundaram_kyc?></td>
			<td><?=$investor_master_data_row->status_dare_sundaram?></td>
			<td><?=$investor_master_data_row->rejection_reason_sundaram?></td>
			<td><?=$investor_master_data_row->account_status?></td>
			<td><?=$investor_master_data_row->acount_status_date?></td>
			<td><?=$investor_master_data_row->email_alert?></td>
			<td><?=$investor_master_data_row->sms_alert?></td>
			<td><?=$investor_master_data_row->document_received?></td>
			<td><?=$investor_master_data_row->document_received_date?></td>
			<td><?=$investor_master_data_row->rejected_date?></td>
			<td><?=$investor_master_data_row->activation_date?></td>
			<td><?=$investor_master_data_row->courier?></td>
			<td><?=$investor_master_data_row->version_no?></td>
			<td><?=$investor_master_data_row->second_applicant_pan?></td>
			<td><?=$investor_master_data_row->second_applicant_name?></td>
			<td><?=$investor_master_data_row->second_applicant_kyc_status?></td>
			<td><?=$investor_master_data_row->second_applicant_kyc_status_description?></td>
			<td><?=$investor_master_data_row->third_applicant_pan?></td>
			<td><?=$investor_master_data_row->third_applicant_name?></td>
			<td><?=$investor_master_data_row->third_applicant_kyc_status?></td>
			<td><?=$investor_master_data_row->third_applicant_kyc_status_description?></td>
			<td><?=$investor_master_data_row->gender?></td>
			<td><?=$investor_master_data_row->investor_type?></td>
			<td><?=$investor_master_data_row->investor_dob?></td>
			<td><?=$investor_master_data_row->mode_of_holding?></td>
			<td><?=$investor_master_data_row->nationality?></td>
			<td><?=$investor_master_data_row->guardian_pan?></td>
			<td><?=$investor_master_data_row->guardian_name?></td>
			<td><?=$investor_master_data_row->guardian_kyc_status?></td>
			<td><?=$investor_master_data_row->guardian_kyc_status_description?></td>
			<td><?=$investor_master_data_row->guardian_rel_minor?></td>
			<td><?=$investor_master_data_row->bank_name?></td>
			<td><?=$investor_master_data_row->ifsc_code?></td>
			<td><?=$investor_master_data_row->micr_code?></td>
			<td><?=$investor_master_data_row->bank_account_holder_name?></td>
			<td><?=$investor_master_data_row->bank_account_no?></td>
			<td><?=$investor_master_data_row->bank_account_type?></td>
			<td><?=$investor_master_data_row->bank_address?></td>
			<td><?=$investor_master_data_row->applied_for_mandate?></td>
			<td><?=$investor_master_data_row->applied_ecs_ach_both?>?></td>
			<td><?=$investor_master_data_row->country?></td>
			<td><?=$investor_master_data_row->pincode?></td>
			<td><?=$investor_master_data_row->city?></td>
			<td><?=$investor_master_data_row->state?></td>
			<td><?=$investor_master_data_row->correspondence_address?></td>
			<td><?=$investor_master_data_row->email_id?></td>
			<td><?=$investor_master_data_row->mobile_no?></td>
			<td><?=$investor_master_data_row->nominee_name?></td>
			<td><?=$investor_master_data_row->nominee_rel_first_applicant?></td>
			<td><?=$investor_master_data_row->status?></td>
			<td><?=$investor_master_data_row->nominee_dob?></td>
			<td><?=$investor_master_data_row->nominee_address?></td>
			<td><?=$investor_master_data_row->nominee_guardian_name?></td>
			<td><?=$investor_master_data_row->rel_with_nominee?></td>
			<td><?=$investor_master_data_row->registration_date?></td>
			<td><?=$investor_master_data_row->ecs_mandate_status?></td>
			<td><?=$investor_master_data_row->ach_mandate_status?></td>
			<td><?=$investor_master_data_row->login_username?></td>
			<td><?=$investor_master_data_row->mode_of_application?></td>
			<td><?=$investor_master_data_row->no_of_sip?></td>
			<td><?=$investor_master_data_row->no_of_lumsum?></td>
			<td><?=$investor_master_data_row->non_kyc_activation_remark?></td>
			<td><?=$investor_master_data_row->myuniverse_ref_id?></td>
			<td><?=$investor_master_data_row->myuniverse_email_id?></td>
			<td><?=$investor_master_data_row->url?></td>
			<td><?=$investor_master_data_row->utm?></td>
			<td><?=$investor_master_data_row->product_page?></td>
			<td><?=$investor_master_data_row->kyc_agency_status?></td>
			<td><?=$investor_master_data_row->date_time?></td>
		</tr>
		<?php
	}
	?>
	</table>
</div>
</div>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
	<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-throttle-debounce/1.1/jquery.ba-throttle-debounce.min.js"></script>
	<script src="<?=base_url()?>assets/js/jquery.stickyheader.js"></script>
</body>
</html>